### ISSUE TITLE
Convert inline SVG to image element

### ISSUE THREAD

**Issue by amanire** [isovera/tfa_nudge#1]
- [x] Create standalone svg file, e.g. `lock-icon.svg` from [the inline SVG code](https://github.com/isovera/tfa_nudge/blob/7.x/tfa_nudge_handler_field_boolean.inc#L83)
- [x] Create standalone svg file, e.g. `warning-icon.svg` from [the inline SVG code](https://github.com/isovera/tfa_nudge/blob/7.x/tfa_nudge_handler_field_boolean.inc#L92)
- [x] Create a render array for the lock icon and return it, something like:

``` php
$build = array(
  '#theme' => 'image',
  '#path' => $image['uri'],
  '#alt' => $image['ImageAlt'],
  '#title' => $image['ImageTitle'],
);
```
- [x] Create a render array for the warning icon as above

**Comment by jillii** [comment]
PR #4

**Comment by amanire** [comment]
See https://github.com/isovera/tfa_nudge/pull/4#discussion-diff-55747347

**Comment by jillii** [comment]
@amanire Whoops, thanks for pointing that out. There's a new commit that fixes the formatting now.

**Comment by amanire** [comment]
@jillii you also need to add the theme key to the array `'#theme' => 'image',`

**Comment by amanire** [comment]
Also https://github.com/isovera/tfa_nudge/pull/4/files#r55751910

**Comment by amanire** [comment]
@jillii https://github.com/isovera/tfa_nudge/pull/4/files#r55752388

**Comment by jillii** [comment]
ok @amanire, the image should work now
